---

  - fail:
      msg: >
        Mail domain must be defined set env variable PRACTICAL_MAIL_DOMAIN
        to your desired domain name
    when: base_domain == ""

  - include_tasks: deps.yml
  - include_tasks: users.yml
  - include_tasks: storage.yml
  - include_tasks: config/hostname.yml
  - include_tasks: config/certificates.yml
  - include_tasks: config/postfix.yml
  - include_tasks: config/dovecot.yml
  - include_tasks: config/filters.yml
  - include_tasks: config/dkim.yml
  - include_tasks: config/services.yml
