---

- name: Create mail storage
  file:
      path: '{{item}}'
      state: directory
      owner: '{{mail_user}}'
      group: '{{mail_group}}'
      mode: 0770
      recurse: yes
  with_items:
    - '{{mail_dir_storage}}'
    - /var/spool/postfix
    - /var/lib/postfix
  notify: restart postfix
